# Generated by Django 6.0.3 on 2026-03-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permission_notes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
