# Generated by Django 6.0.3 on 2026-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_campaign_lead_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
