# Generated by Django 6.0.3 on 2026-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_last_contacted_at_lead_last_contacted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent')], default='agent', max_length=50),
        ),
    ]
