# Generated by Django 6.0.3 on 2026-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
