# Generated by Django 5.2.4 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_internaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
