# Generated by Django 5.2.4 on 2026-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
