# Generated by Django 5.2.4 on 2026-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_quotation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='executive_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
